# Assignment_Numpy

## 1.Introduction

This assignment will help you to consolidate the concepts learnt in the session.

## 2.Problem Statement

(1) Write a function so that the columns of the output matrix are powers of the input
vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.
HINT: Such a matrix with a geometric progression in each row is named for Alexandre-
Theophile Vandermonde.

==============================================================================================

(2) Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of
the given sequence is defined as follows:
The moving average sequence has n-k+1 elements as shown below.
The moving averages with k=4 of a ten-value sequence (n=10) is shown below
i 1 2 3 4 5 6 7 8 9 10
===== == == == == == == == == == ==
Input 10 20 30 40 50 60 70 80 90 100
y1 25 = (10+20+30+40)/4
y2 35 = (20+30+40+50)/4
y3 45 = (30+40+50+60)/4
y4 55 = (40+50+60+70)/4
y5 65 = (50+60+70+80)/4
y6 75 = (60+70+80+90)/4
y7 85 = (70+80+90+100)/4
Thus, the moving average sequence has n-k+1=10-4+1=7 values.
Question: Write a function to find moving average in an array over a window:
Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.






In [ ]:
"""
Question_1:

Write a function so that the columns of the output matrix are powers of the input vector.
The order of the powers is determined by the increasing boolean argument. 
Specifically, when increasing is False, the i-th output column is the input vector 
raised element-wise to the power of N - i - 1. 
HINT: Such a matrix with a geometric progression in each row is named 
for Alexandre- Theophile Vandermonde.

"""

In [10]:
import numpy as np

In [15]:
l=[]

n=int(input("Number of items in an Array:"))

for i in range(0,n):
    
    num=int(input("Number:"))
    
    l.append(num)
    
print("List:",l)

arr=np.array(l)

print("Array is:",arr)
def matrix():
    
    mat= np.vander(arr,N=4) # default value of N is equal to length of an Array. Here N=3.
    print("alexandre theophile vandermonde matrix is:\n",mat)
    
matrix()


Number of items in an Array:7
Number:1
Number:4
Number:8
Number:2
Number:63
Number:7
Number:4
List: [1, 4, 8, 2, 63, 7, 4]
Array is: [ 1  4  8  2 63  7  4]
alexandre theophile vandermonde matrix is:
 [[     1      1      1      1]
 [    64     16      4      1]
 [   512     64      8      1]
 [     8      4      2      1]
 [250047   3969     63      1]
 [   343     49      7      1]
 [    64     16      4      1]]


In [ ]:
"""
Question_2:

Given a sequence of n values x1, x2, ..., xn and a window size k>0, 
the k-th moving average of the given sequence is defined as follows: 
The moving average sequence has n-k+1 elements as shown below. 
The moving averages with k=4 of a ten-value sequence (n=10) is shown below
i 1 2 3 4 5 6 7 8 9 10 
===== == == == == == == == == == == 
Input 10 20 30 40 50 60 70 80 90 100 
y1 25 = (10+20+30+40)/4 
y2 35 = (20+30+40+50)/4 
y3 45 = (30+40+50+60)/4 
y4 55 = (40+50+60+70)/4 
y5 65 = (50+60+70+80)/4 
y6 75 = (60+70+80+90)/4 
y7 85 = (70+80+90+100)/4 
Thus, the moving average sequence has n-k+1=10-4+1=7 values. 
Question: Write a function to find moving average in an array over a window:
Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.
"""

In [16]:
def moving_avg():
    
    l=[3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
    arr=np.array(l)
    k=3
    n=13
    MA=n-k+1
    i=0
    l1=[]

    while i < MA:
        tw=arr[i:i+k]
        wa=sum(tw)/k
        l1.append(wa)
        i=i+1
    print(l1)
moving_avg()

[5.0, 4.666666666666667, 5.666666666666667, 6.666666666666667, 9.666666666666666, 28.666666666666668, 49.333333333333336, 72.66666666666667, 84.0, 93.33333333333333, 116.33333333333333]
