In [11]:
import numpy as np
l=[]

n=int(input("Number of items in an Array:"))

for i in range(0,n):
    
    num=int(input("Number:"))
    
    l.append(num)
    
print("List:",l)

arr=np.array(l)

print("Array is:",arr)
def matrix():
    
    mat= np.vander(arr,N=3) # default value of N is equal to length of an Array. Here N=3.
    print("alexandre theophile vandermonde matrix is:\n",mat)
    
matrix()


Number of items in an Array:5
Number:2
Number:3
Number:5
Number:4
Number:9
List: [2, 3, 5, 4, 9]
Array is: [2 3 5 4 9]
alexandre theophile vandermonde matrix is:
 [[ 4  2  1]
 [ 9  3  1]
 [25  5  1]
 [16  4  1]
 [81  9  1]]


In [ ]:

7